Vagrant.configure(2) do |config|
  config.vm.box = "https://cloud-images.ubuntu.com/vagrant/wily/current/wily-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network "private_network", ip: "192.168.120.120"
  config.vm.synced_folder ".", "/vagrant", nfs: true
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/dmrz/misc/master/vagrant/provision.sh"
end
